from kepocnhh/debian-amd64:3

copy ex/util ex/util
copy ex/github/assemble/actions/run.sh ex/github/assemble/actions/run.sh
copy ex/github/assemble/repository.sh ex/github/assemble/repository.sh
copy ex/github/assemble/repository/pages.sh ex/github/assemble/repository/pages.sh
copy internal/check/github/assemble/repository/pages/check.sh .

cmd ./check.sh
