from kepocnhh/debian-amd64:3

copy ex/util ex/util
copy ex/github/assemble/pr.sh ex/github/assemble/pr.sh
copy ex/github/pr/close.sh ex/github/pr/close.sh
copy internal/check/ex/github/pr/close/check.sh .

cmd ./check.sh
