from kepocnhh/debian-amd64:3

copy ex/util ex/util
copy ex/github/workflow/tag/test/on_failed.sh ex/github/workflow/tag/test/on_failed.sh
copy internal/check/github/workflow/tag/test/on_failed/check.sh .

cmd ./check.sh
