from kepocnhh/gradle-amd64:7.5.1

copy ex/util ex/util
copy ex/github/assemble/repository.sh ex/github/assemble/repository.sh
copy ex/kotlin/lib/project/diagnostics/unit_test.sh ex/kotlin/lib/project/diagnostics/unit_test.sh
copy internal/check/kotlin/lib/project/diagnostics/unit_test/check.sh .

cmd ./check.sh
