from kepocnhh/gradle-amd64:7.5.1

copy ex/util ex/util
copy ex/github/assemble/repository.sh ex/github/assemble/repository.sh
copy ex/kotlin/lib/project/verify/pre.sh ex/kotlin/lib/project/verify/pre.sh
copy internal/check/ex/kotlin/lib/project/verify/pre/check.sh .

cmd ./check.sh
