from kepocnhh/debian-amd64:3

copy ex/util ex/util
copy ex/github/pr/check_state.sh ex/github/pr/check_state.sh
copy ex/github/workflow/pr/check_state.sh ex/github/workflow/pr/check_state.sh
copy internal/check/github/workflow/pr/check_state/check.sh .

cmd ./check.sh
