from kepocnhh/debian-amd64:3

copy ex/util ex/util
copy ex/github/assemble/repository.sh ex/github/assemble/repository.sh
copy ex/github/tag/test.sh ex/github/tag/test.sh
copy ex/github/workflow/tag/test.sh ex/github/workflow/tag/test.sh
copy internal/check/ex/github/workflow/tag/test/check.sh .

cmd ./check.sh
