from kepocnhh/debian-amd64:3

copy ex/util ex/util
copy ex/github/assemble/actions/run/repository.sh ex/github/assemble/actions/run/repository.sh
copy ex/github/assemble/repository/pages.sh ex/github/assemble/repository/pages.sh
copy ex/github/assemble/worker.sh ex/github/assemble/worker.sh
copy ex/github/tag/test.sh ex/github/tag/test.sh
copy ex/kotlin/lib/project/diagnostics/common.sh ex/kotlin/lib/project/diagnostics/common.sh
copy ex/github/diagnostics/report.sh ex/github/diagnostics/report.sh
copy internal/check/ex/github/diagnostics/report/check.sh .

cmd ./check.sh
