from kepocnhh/debian-amd64:3

copy ex/util ex/util
copy ex/github/assemble/pr.sh ex/github/assemble/pr.sh
copy ex/github/pr/comment.sh ex/github/pr/comment.sh
copy internal/check/github/pr/comment/check.sh .

cmd ./check.sh
