from kepocnhh/debian-amd64:3

copy ex/util ex/util
copy ex/github/assemble/repository.sh ex/github/assemble/repository.sh
copy ex/github/assemble/commit.sh ex/github/assemble/commit.sh
copy internal/check/github/assemble/commit/check.sh .

cmd ./check.sh
