from kepocnhh/debian-amd64:3

copy ex/util ex/util
copy ex/github/assemble/worker.sh ex/github/assemble/worker.sh
copy ex/github/release.sh ex/github/release.sh
copy internal/check/ex/github/release/check.sh .

cmd ./check.sh
