from kepocnhh/debian-amd64:3

copy ex/util ex/util
copy ex/github/assemble/actions/run.sh ex/github/assemble/actions/run.sh
copy ex/github/assemble/repository.sh ex/github/assemble/repository.sh
copy ex/github/assemble/repository/owner.sh ex/github/assemble/repository/owner.sh
copy internal/check/github/assemble/repository/owner/check.sh .

cmd ./check.sh
