from kepocnhh/debian-amd64:3

copy ex/util ex/util
copy ex/github/assemble/repository.sh ex/github/assemble/repository.sh
copy ex/github/workflow/pr/commit.sh ex/github/workflow/pr/commit.sh
copy ex/github/workflow/pr/merge.sh ex/github/workflow/pr/merge.sh
copy internal/check/ex/github/workflow/pr/commit/check.sh .

cmd ./check.sh
