from kepocnhh/gradle-amd64:7.5.1

copy ex/util ex/util
copy ex/github/assemble/repository.sh ex/github/assemble/repository.sh
copy ex/github/tag/test.sh ex/github/tag/test.sh
copy internal/check/github/tag/test/check.sh .

cmd ./check.sh
