from kepocnhh/debian-amd64:3

copy ex/util ex/util
copy ex/github/assemble/actions/run.sh ex/github/assemble/actions/run.sh
copy internal/check/github/assemble/actions/run/check.sh check.sh

cmd ./check.sh
