from kepocnhh/debian-amd64:3

copy ex/util ex/util
copy ex/github/release/upload/assets.sh ex/github/release/upload/assets.sh
copy internal/check/github/release/upload/assets/check.sh .

cmd ./check.sh
