from kepocnhh/debian-amd64:3

copy ex/util ex/util
copy ex/notification/telegram/send_file.sh ex/notification/telegram/send_file.sh
copy internal/check/notification/telegram/send_file/check.sh .

cmd ./check.sh
