from kepocnhh/gradle-amd64:7.5.1

copy ex/util ex/util
copy ex/github/assemble/actions/run/repository.sh ex/github/assemble/actions/run/repository.sh
copy ex/github/assemble/worker.sh ex/github/assemble/worker.sh
copy ex/kotlin/lib/project/diagnostics/common.sh ex/kotlin/lib/project/diagnostics/common.sh
copy ex/github/diagnostics/report.sh ex/github/diagnostics/report.sh
copy internal/check/github/diagnostics/report/check.sh .

cmd ./check.sh
