name: Pull request to unstable

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - unstable

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo "REPOSITORY_OWNER=${{github.event.repository.owner.login}}" >> "$GITHUB_ENV"
          echo "REPOSITORY_NAME=${{github.event.repository.name}}" >> "$GITHUB_ENV"
          mkdir -p workdir/prepare/repository
      - working-directory: workdir/prepare/repository
        env:
          GIT_BRANCH_SRC: ${{github.event.pull_request.head.ref}}
        run: |
          git init
          VCS_PAT="$(echo "${{secrets.VCS_TOKENS}}" | base64 -d | jq -Mcr .github.continuousi)"
          git remote add origin "https://${VCS_PAT}@github.com/${REPOSITORY_OWNER}/${REPOSITORY_NAME}.git"
          git fetch origin "$GIT_BRANCH_SRC"
          git checkout "$GIT_BRANCH_SRC"
      - working-directory: workdir/prepare
        env:
          VCS_DOMAIN: 'https://api.github.com'
          PR_NUMBER: ${{github.event.pull_request.number}}
        run: |
          mkdir ex; cp -r repository/ex/util ex/util
          export VCS_PAT="$(echo "${{secrets.VCS_TOKENS}}" | base64 -d | jq -Mcr .github.continuousi)"
          repository/ex/github/assemble/worker.sh
          repository/ex/github/assemble/repository.sh
          repository/ex/github/assemble/pr.sh
          repository/ex/github/workflow/pr/merge.sh
      - working-directory: workdir
        run: |
          mv prepare/repository repository
          rm -rf prepare
          cp -r repository/ex ex
      - working-directory: workdir
        env:
          VCS_DOMAIN: 'https://api.github.com'
        run: |
          ex/github/assemble/repository.sh
          for it in $(cat repository/internal/env); do export $it; done
          ex/util/require VERSION
          ex/github/tag/test.sh "${VERSION}-UNSTABLE"
      - working-directory: workdir
        env:
          VCS_DOMAIN: 'https://api.github.com'
          PR_NUMBER: ${{github.event.pull_request.number}}
        run: |
          export VCS_PAT="$(echo "${{secrets.VCS_TOKENS}}" | base64 -d | jq -Mcr .github.continuousi)"
          ex/github/assemble/worker.sh
          ex/github/assemble/pr.sh
          export CI_BUILD_ID=$GITHUB_RUN_ID
          ex/github/assemble/actions/run.sh
      - working-directory: workdir
        env:
          PR_NUMBER: ${{github.event.pull_request.number}}
        run: |
          ex/github/workflow/pr/commit.sh
          for it in $(cat repository/internal/env); do export $it; done
          ex/util/require VERSION
          mkdir -p assemble/project/artifact
          $(ISSUER="$(pwd)" && cd "$ISSUER" && zip -r9 "assemble/project/artifact/CIExtension-${VERSION}-UNSTABLE.zip" ci ex > /dev/null)
          git -C repository push
          ex/github/assemble/commit.sh
      - working-directory: workdir
        run: |
          for it in $(cat repository/internal/env); do export $it; done
          ex/util/require VERSION
          BODY="{}"
          TAG="${VERSION}-UNSTABLE"
          . ex/util/json -f assemble/vcs/commit.json -sfs .sha GIT_COMMIT_SHA
          . ex/util/json_merge -v BODY ".name=\"$TAG\"" ".tag_name=\"$TAG\"" ".target_commitish=\"$GIT_COMMIT_SHA\""
          . ex/util/json -f assemble/vcs/actions/run.json -si .run_number CI_BUILD_NUMBER -sfs .html_url CI_BUILD_HTML_URL
          . ex/util/json_merge -v BODY ".body=\"CI build [#$CI_BUILD_NUMBER]($CI_BUILD_HTML_URL)\""
          . ex/util/json_merge -v BODY '.draft=false' '.prerelease=true'
          mkdir assemble/github
          export VCS_PAT="$(echo "${{secrets.VCS_TOKENS}}" | base64 -d | jq -Mcr .github.continuousi)"
          ex/github/release.sh "$BODY"
          ASSET_NAME="CIExtension-${VERSION}-UNSTABLE.zip"
          ASSETS="[]"
          ASSET="{}"
          . ex/util/json_merge -v ASSET ".name=\"$ASSET_NAME\"" ".label=\"$ASSET_NAME\"" ".path=\"assemble/project/artifact/$ASSET_NAME\""
          . ex/util/json_merge -v ASSETS ".+=[$ASSET]"
          ex/github/release/upload/asset.sh "$ASSETS"
      - working-directory: workdir
        run: |
          echo "Not implemented! check_state"; exit 1 # todo
          echo "Not implemented! on_success"; exit 1 # todo
