name: Pull request to unstable

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - unstable

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      VCS_DOMAIN: 'https://api.github.com'
      PR_NUMBER: ${{github.event.pull_request.number}}
    steps:
      - name: Set up repository
        env:
          REPOSITORY_OWNER: ${{github.event.repository.owner.login}}
          REPOSITORY_NAME: ${{github.event.repository.name}}
        run: |
          VCS_PAT="$(echo "${{secrets.VCS_TOKENS}}" | base64 -d | jq -Mcr .github.continuousi)"
          mkdir -p workdir/repository
          git -C workdir/repository init
          git -C workdir/repository \
           remote add origin "https://${VCS_PAT}@github.com/${REPOSITORY_OWNER}/${REPOSITORY_NAME}.git"
          git -C workdir/repository fetch origin "${{github.event.pull_request.head.ref}}"
          git -C workdir/repository checkout FETCH_HEAD
          mkdir workdir/ex
          cp -r workdir/repository/ex/util workdir/ex/
      - name: Pull request merge
        working-directory: workdir
        env:
          REPOSITORY_OWNER: ${{github.event.repository.owner.login}}
          REPOSITORY_NAME: ${{github.event.repository.name}}
        run: |
          export VCS_PAT
          . ex/util/json --base64 "${{secrets.VCS_TOKENS}}" -sfs .github.continuousi VCS_PAT
          repository/internal/shell/workflow/pull/request/prepare/merge.sh
          IMAGE_NAME="${REPOSITORY_OWNER}.${REPOSITORY_NAME}.pr.unstable"
          echo "IMAGE_NAME=${IMAGE_NAME,,}" >> $GITHUB_ENV
      - name: Build image
        working-directory: workdir
        env:
          REPOSITORY_OWNER: ${{github.event.repository.owner.login}}
          REPOSITORY_NAME: ${{github.event.repository.name}}
        run: |
          . ex/util/json --base64 "${{secrets.VCS_TOKENS}}" -sfs .github.continuousi VCS_PAT
          docker build --no-cache \
           --build-arg="VCS_PAT=$VCS_PAT" \
           --build-arg="REPOSITORY_OWNER=$REPOSITORY_OWNER" \
           --build-arg="REPOSITORY_NAME=$REPOSITORY_NAME" \
           --build-arg="GIT_BRANCH_SRC=${{github.event.pull_request.head.ref}}" \
           --build-arg="VCS_DOMAIN=$VCS_DOMAIN" \
           --build-arg="PR_NUMBER=$PR_NUMBER" \
           --build-arg="CI_BUILD_ID=$GITHUB_RUN_ID" \
           -f='repository/internal/docker/workflow/pull/request/Dockerfile' \
           -t="${IMAGE_NAME}:${GITHUB_RUN_ID}" .
      - name: Run container
        working-directory: workdir
        run: |
          . ex/util/json --base64 "${{secrets.VCS_TOKENS}}" \
           -sfs .github.continuousi VCS_PAT
          . ex/util/json --base64 "${{secrets.TELEGRAM}}" \
           -si .bot.continuousibot.id TELEGRAM_BOT_ID \
           -sfs .bot.continuousibot.token TELEGRAM_BOT_TOKEN \
           -si .chat.kepocnhh.id TELEGRAM_CHAT_ID
          KEY_ALIAS='debug'
          . ex/util/json --base64 "$(cat keystores.json.base64)" \
           -sfs ".${KEY_ALIAS}.base64" KEYSTORE \
           -sfs ".${KEY_ALIAS}.password" KEYSTORE_PASSWORD
          . ex/util/json --base64 "$(cat fingerprints.json.base64)" \
           -sfs ".key.${KEY_ALIAS}.x509.sha512" KEY_X509_SHA512
          docker run --rm \
           -e VCS_PAT="$VCS_PAT" \
           -e PR_NUMBER="$PR_NUMBER" \
           -e TELEGRAM_BOT_ID="$TELEGRAM_BOT_ID" \
           -e TELEGRAM_BOT_TOKEN="$TELEGRAM_BOT_TOKEN" \
           -e TELEGRAM_CHAT_ID="$TELEGRAM_CHAT_ID" \
           -e KEYSTORE="$KEYSTORE" \
           -e KEYSTORE_PASSWORD="$KEYSTORE_PASSWORD" \
           -e KEY_X509_SHA512="$KEY_X509_SHA512" \
           --name="container.${IMAGE_NAME}" "${IMAGE_NAME}:${GITHUB_RUN_ID}" \
           repository/internal/shell/workflow/pull/request/unstable.sh
      - name: Not implemented!
        run: echo "Not implemented!"; exit 1
      - name: GitHub release
        working-directory: workdir
        run: |
          for it in $(cat repository/internal/env); do export $it; done
          ex/util/require VERSION
          BODY='{}'
          TAG="${VERSION}-UNSTABLE"
          . ex/util/json -f assemble/vcs/commit.json -sfs .sha GIT_COMMIT_SHA
          . ex/util/json -f assemble/vcs/actions/run.json \
           -si .run_number CI_BUILD_NUMBER -sfs .html_url CI_BUILD_HTML_URL
          . ex/util/json_merge -v BODY \
           ".name=\"$TAG\"" ".tag_name=\"$TAG\"" \
           ".target_commitish=\"$GIT_COMMIT_SHA\"" \
           ".body=\"CI build [#$CI_BUILD_NUMBER]($CI_BUILD_HTML_URL)\"" \
           '.draft=false' '.prerelease=true'
          mkdir assemble/github
          export VCS_PAT
          . ex/util/json --base64 "${{secrets.VCS_TOKENS}}" -sfs .github.continuousi VCS_PAT
          ex/github/release.sh "$BODY"
          ASSET_NAME="CIExtension-${VERSION}-UNSTABLE.zip"
          ASSETS='[]'
          ASSET='{}'
          . ex/util/json_merge -v ASSET \
           ".name=\"$ASSET_NAME\"" ".label=\"$ASSET_NAME\"" \
           ".path=\"assemble/project/artifact/$ASSET_NAME\""
          . ex/util/json_merge -v ASSETS ".+=[$ASSET]"
          echo "Not implemented! sign"; exit 1 # todo
          ex/github/release/upload/asset.sh "$ASSETS"
      - name: On success
        working-directory: workdir
        env:
          PR_NUMBER: ${{github.event.pull_request.number}}
        run: |
          ex/github/workflow/pr/check_state.sh 'closed'
          for it in $(cat repository/internal/env); do export $it; done
          ex/util/require VERSION
          TAG="${VERSION}-UNSTABLE"
          . ex/util/json -f assemble/vcs/actions/run.json \
           -si .run_number CI_BUILD_NUMBER \
           -sfs .html_url CI_BUILD_HTML_URL
          . ex/util/json -f assemble/vcs/repository.json \
           -sfs .name REPOSITORY_NAME \
           -sfs .html_url REPOSITORY_HTML_URL
          MESSAGE="Merged by CI build [#$CI_BUILD_NUMBER]($CI_BUILD_HTML_URL) \
           - release [$TAG]($REPOSITORY_HTML_URL/releases/tag/$TAG)"
          ex/github/pr/comment.sh "$MESSAGE"
          echo "Not implemented! on_success"; exit 1 # todo
