name: Pull request to unstable

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - unstable

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      VCS_DOMAIN: 'https://api.github.com'
      PR_NUMBER: ${{github.event.pull_request.number}}
    steps:
      - name: Set up repository
        env:
          REPOSITORY_OWNER: ${{github.event.repository.owner.login}}
          REPOSITORY_NAME: ${{github.event.repository.name}}
        run: |
          VCS_PAT="$(echo "${{secrets.VCS_TOKENS}}" | base64 -d | jq -Mcr .github.continuousi)"
          mkdir -p workdir/repository
          git -C workdir/repository init
          git -C workdir/repository \
           remote add origin "https://${VCS_PAT}@github.com/${REPOSITORY_OWNER}/${REPOSITORY_NAME}.git"
          git -C workdir/repository fetch origin "${{github.event.pull_request.head.ref}}"
          git -C workdir/repository checkout FETCH_HEAD
          mkdir workdir/ex
          cp -r workdir/repository/ex/util workdir/ex/
      - name: Pull request merge
        working-directory: workdir
        env:
          REPOSITORY_OWNER: ${{github.event.repository.owner.login}}
          REPOSITORY_NAME: ${{github.event.repository.name}}
        run: |
          export VCS_PAT
          . ex/util/json --base64 "${{secrets.VCS_TOKENS}}" -sfs .github.continuousi VCS_PAT
          repository/internal/shell/workflow/pull/request/prepare/merge.sh
          IMAGE_NAME="${REPOSITORY_OWNER}.${REPOSITORY_NAME}.pr.unstable"
          echo "IMAGE_NAME=${IMAGE_NAME,,}" >> $GITHUB_ENV
      - name: Build image
        working-directory: workdir
        env:
          REPOSITORY_OWNER: ${{github.event.repository.owner.login}}
          REPOSITORY_NAME: ${{github.event.repository.name}}
        run: |
          . ex/util/json --base64 "${{secrets.VCS_TOKENS}}" -sfs .github.continuousi VCS_PAT
          docker build --no-cache \
           --build-arg="VCS_PAT=$VCS_PAT" \
           --build-arg="REPOSITORY_OWNER=$REPOSITORY_OWNER" \
           --build-arg="REPOSITORY_NAME=$REPOSITORY_NAME" \
           --build-arg="GIT_BRANCH_SRC=${{github.event.pull_request.head.ref}}" \
           --build-arg="VCS_DOMAIN=$VCS_DOMAIN" \
           --build-arg="PR_NUMBER=$PR_NUMBER" \
           --build-arg="CI_BUILD_ID=$GITHUB_RUN_ID" \
           -f='repository/internal/docker/workflow/pull/request/Dockerfile' \
           -t="${IMAGE_NAME}:${GITHUB_RUN_ID}" .
      - name: Run container
        working-directory: workdir
        run: |
          . ex/util/json --base64 "${{secrets.VCS_TOKENS}}" \
           -sfs .github.continuousi VCS_PAT
          . ex/util/json --base64 "${{secrets.TELEGRAM}}" \
           -si .bot.continuousibot.id TELEGRAM_BOT_ID \
           -sfs .bot.continuousibot.token TELEGRAM_BOT_TOKEN \
           -si .chat.kepocnhh.id TELEGRAM_CHAT_ID
          KEY_ALIAS='debug'
          . ex/util/json --base64 "${{secrets.KEYSTORES}}" \
           -sfs ".${KEY_ALIAS}.base64" KEYSTORE \
           -sfs ".${KEY_ALIAS}.password" KEYSTORE_PASSWORD
          . ex/util/json --base64 "${{secrets.FINGERPRINTS}}" \
           -sfs ".key.${KEY_ALIAS}.x509.sha512" KEY_X509_SHA512
          docker run --rm \
           -e VCS_PAT="$VCS_PAT" \
           -e PR_NUMBER="$PR_NUMBER" \
           -e TELEGRAM_BOT_ID="$TELEGRAM_BOT_ID" \
           -e TELEGRAM_BOT_TOKEN="$TELEGRAM_BOT_TOKEN" \
           -e TELEGRAM_CHAT_ID="$TELEGRAM_CHAT_ID" \
           -e KEYSTORE="$KEYSTORE" \
           -e KEYSTORE_PASSWORD="$KEYSTORE_PASSWORD" \
           -e KEY_X509_SHA512="$KEY_X509_SHA512" \
           --name="container.${IMAGE_NAME}" "${IMAGE_NAME}:${GITHUB_RUN_ID}" \
           repository/internal/shell/workflow/pull/request/unstable.sh
