from kepocnhh/debian-amd64:3

copy ex/util ex/util
copy ex/github/pr/close.sh ex/github/pr/close.sh
copy ex/github/assemble/actions/run.sh ex/github/assemble/actions/run.sh
copy ex/github/pr/comment.sh ex/github/pr/comment.sh
copy ex/github/assemble/actions/run/repository.sh ex/github/assemble/actions/run/repository.sh
copy ex/github/assemble/repository/owner.sh ex/github/assemble/repository/owner.sh
copy ex/github/assemble/pr/commit.sh ex/github/assemble/pr/commit.sh
copy ex/github/assemble/worker.sh ex/github/assemble/worker.sh
copy ex/notification/telegram/send_message.sh ex/notification/telegram/send_message.sh
copy ex/github/assemble/pr.sh ex/github/assemble/pr.sh
copy ex/github/workflow/tag/test/on_failed.sh ex/github/workflow/tag/test/on_failed.sh
copy internal/check/ex/github/workflow/tag/test/on_failed/check.sh .

cmd ./check.sh
